namespace:
appName: Bobbycar
ocpDomain:

datagrid:
  replicas: 1
  type: DataGrid
  cpu: '500m'
  memory: 1Gi

amqBroker:
  instances: 1
  console:
    expose: true  

kafka: 
  cluster:
    brokerReplicas: 2
    zookeeperReplicas: 3
  bridge: 
    replicas: 1
    port: 8080
  topic:
    gps:
      name: bobbycar-gps
      partitions: 1
      replicas: 1
      retention: 60000
    metrics:
      name: bobbycar-metrics
      partitions: 1
      replicas: 1
      retention: 60000
    zonechange:
      name: bobbycar-zonechange
      partitions: 1
      replicas: 1
      retention: 300000

global:
  cluster: openshift
  drogueCloud:
    useServiceCA: true
    keycloak:
      insecure: true

drogueCloudCore:
  console:
    localCertificates: true

  endpoints:
    coap:
      ingress:
        port: 443
    mqtt:
      ingress:
        port: 443
    mqttWs:
      ingress:
        port: 443
    mqttWsBrowser:
      ingress:
        port: 443
    http:
      ingress:
        port: 443

  integrations:
    websocket:
      service:
        insecure: true
      ingress:
        insecure: true
        port: 80
    mqtt:
      ingress:
        port: 443
    mqttWsBrowser:
      ingress:
        port: 443
    mqttWs:
      ingress:
        port: 443

  services:
    console:
      service:
        insecure: true
      ingress:
        insecure: true
        port: 80
    command:
      service:
        insecure: true
      ingress:
        insecure: true
        port: 80
    registry:
      service:
        insecure: true
    api:
      ingress:
        insecure: true
        port: 80
    sso:
      ingress:
        insecure: true
        port: 80
